# Generated by Django 4.1 on 2023-02-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='utternace_vector',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
