# Generated by Django 4.1 on 2023-04-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_response_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=8192)),
                ('amy_text', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='AmyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amy_text', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('user_text', models.CharField(max_length=8192)),
                ('created_at', models.DateTimeField(verbose_name='Time')),
                ('amy_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.amyprompt')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_mode',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Utterance',
        ),
        migrations.AddField(
            model_name='amyresponse',
            name='user_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.userinput'),
        ),
    ]
