# Generated by Django 4.1 on 2023-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_utterance_utternace_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='utternace_vector',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
