# Generated by Django 4.1 on 2023-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userinput_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.CharField(default='', max_length=8192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='chat_mode',
            field=models.CharField(default='converse', max_length=25),
            preserve_default=False,
        ),
    ]
