# Generated by Django 4.1 on 2023-06-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_profile_about_you_userinput_chat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_summary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
